"""Add work_start_time and work_end_time to tenants

Revision ID: fa6aec90ba20
Revises: '0001'
Create Date: 2025-07-18 17:15:46.063596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa6aec90ba20'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('work_start_time', sa.Time(), nullable=True))
    op.add_column('tenants', sa.Column('work_end_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'work_end_time')
    op.drop_column('tenants', 'work_start_time')
    # ### end Alembic commands ###